name: pinjamtech_app
description: "PinjamTech Rental Service"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  local_auth: ^2.1.8
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.5+1
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  image_picker: ^1.0.4
  supabase_flutter: ^2.10.3
  path: ^1.8.0
  table_calendar: ^3.2.0
  geolocator: ^14.0.2
  
  
    # NEW OFFLINE DEPENDENCIES
  sqflite: ^2.3.0
  connectivity_plus: ^4.0.2
  internet_connection_checker: ^1.0.0+1



flutter:
  uses-material-design: true


  